version: '3'
services:
  excelconvertor:
    build: .
    ports:
      - 8900:8900
    links:
      - "activemq:activemq"

  activemq:
    image: ivonet/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
     - ACTIVEMQ_MIN_MEMORY=512
     - ACTIVEMQ_MAX_MEMORY=2048
     - ACTIVEMQ_ENABLED_AUTH=false
     - ACTIVEMQ_ADMIN_LOGIN=admin
     - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
     - ./volumes/log/activemq:/var/log/activemq

